name: Build the package using cmake then documentation

on:
  workflow_dispatch:

    

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ] 
        python-version: ["3.12", ] 

    runs-on: ${{ matrix.platform }}


    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4

      - name: Setup dev env
        run: |
            sudo apt-get update
            sudo apt-get -y install cmake gcc g++
            sudo apt-get -y install python3.12 python3.12-dev python3.12-pip
            python3.12 -m pip install --upgrade pip
            python3.12 -m pip install breathe
            python3.12 -m pip install sphinx_rtd_theme sphinx 
            python3.12 -m pip install numpy
            python3.12 -m pip install doxygen



      - name: Build library 
        run: |
            mkdir build 
            cd build 
            cmake .. -DAARE_SYSTEM_LIBRARIES=ON -DAARE_DOCS=ON 
            make -j 2 
            make docs







