name: Build on RHEL9

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    container:
      image: gitea.psi.ch/images/rhel9-developer-gitea-actions
    steps:
      - uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          dnf install -y cmake python3.12 python3.12-devel python3.12-pip
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install pytest
          python3.12 -m pip install numpy 


      - name: Build library 
        run: |
            mkdir build && cd build
            cmake .. -DAARE_PYTHON_BINDINGS=ON -DAARE_TESTS=ON
            make -j 2 

      - name: C++ unit tests
        working-directory: ${{gitea.workspace}}/build
        run: ctest

      - name: Python unit tests
        working-directory: ${{gitea.workspace}}
        run: python3.12 -m pytest ${{gitea.workspace}}/python/tests/