name: Build on local RHEL9

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "detectors-software-RH9"
    steps:
      - uses: actions/checkout@v4

      - name: Build library 
        run: |
            mkdir build && cd build
            cmake  -DAARE_PYTHON_BINDINGS=ON -DPython_EXECUTABLE=/usr/bin/python3.13 -DPython_INCLUDE_DIR=/usr/include/python3.13 -DPython_LIBRARY=/usr/lib64/libpython3.13.so ..
            make -j 2 

      - name: Deploy to NFS update server
        if: gitea.ref == 'refs/heads/developer'
        run: |
            sftp -r gitea_runner@mpc2935:/aare/RH9 <<< $'put build/aare'