name: Build on RHEL9

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildh:
    runs-on: "ubuntu-latest"
    container:
      image: container.psi.ch/images/rhel9-developer-github-actions
    steps:
      - uses: actions/checkout@v4
      - name: Setup dev env
        run: |
            sudo apt-get update
            sudo apt-get -y install cmake gcc g++
      

      - name: Build library 
        run: |
            mkdir build 
            cd build 
            cmake .. 
            make -j 2 

