name: Build on RHEL9

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildh:
    runs-on: "ubuntu-latest"
    container:
      image: gitea.psi.ch/images/rhel9-developer-gitea-actions
    steps:
      - uses: actions/checkout@v4

      - name: Build library 
        run: |
            mkdir build 
            cd build 
            cmake3 .. 
            make -j 2 

