python:
    - 3.11
    - 3.11
    - 3.11
    - 3.12
    - 3.12
    - 3.12
    - 3.13


    
numpy: 
    - 1.26
    - 2.0
    - 2.1
    - 1.26
    - 2.0
    - 2.1
    - 2.1


zip_keys:
    - python
    - numpy

pin_run_as_build:
  numpy: x.x
  python: x.x