

package:
  name: aare_software
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ..

build:
  number: 0
  binary_relocation: True
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    # - qt 5.*
    # - xorg-libx11
    # - xorg-libice
    # - xorg-libxext
    # - xorg-libsm
    # - xorg-libxau
    # - xorg-libxrender
    # - xorg-libxfixes
    # - {{ cdt('mesa-libgl-devel') }}      # [linux]
    # - {{ cdt('mesa-libegl-devel') }}     # [linux]
    # - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # - {{ cdt('libselinux') }}            # [linux]
    # - {{ cdt('libxdamage') }}            # [linux]
    # - {{ cdt('libxxf86vm') }}            # [linux]
    # - expat

  host:
    # - libstdcxx-ng
    # - libgcc-ng
    # - xorg-libx11
    # - xorg-libice
    # - xorg-libxext
    # - xorg-libsm
    # - xorg-libxau
    # - xorg-libxrender
    # - xorg-libxfixes
    # - expat

  run:
    # - libstdcxx-ng
    # - libgcc-ng 


outputs:
  - name: aarelib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - catch2
        - zstd

        # - libstdcxx-ng
        # - libgcc-ng


      run: 
        # - libstdcxx-ng
        # - libgcc-ng

  # - name: aare

  #   script: build_pylib.sh

  #   requirements:
  #     build:
  #       - python
  #       - {{ compiler('c') }}
  #       - {{compiler('cxx')}}
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - setuptools
  #       - pybind11=2.11

  #     host:
  #       - python
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - pybind11=2.11


  #     run:
  #       - libstdcxx-ng
  #       - libgcc-ng
  #       - python
  #       - numpy
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}


  #   test:
  #     imports:
  #       - slsdet

  