source:
  path: ../

{% set version = load_file_regex(load_file = 'VERSION', regex_pattern = '(\d+(?:\.\d+)*(?:[\+\w\.]+))').group(1) %}
package:
  name: aare
  version: {{version}}

source:
  path: ..

build:
  number: 0
  script:
    - unset CMAKE_GENERATOR && {{ PYTHON }} -m pip install . -vv 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - python
    - pip
    - numpy=2.1
    - scikit-build-core
    - pybind11 >=2.13.0
    - matplotlib # needed in host to solve the environment for run

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib
    


test:
  imports:
    - aare
  requires:
    - pytest
    - boost-histogram 
  source_files:
    - python/tests
  commands:
    - python -m pytest python/tests

about:
  summary: Data analysis library for hybrid pixel detectors from PSI 
