package:
  name: aare
  version: 2025.4.1 #TODO! how to not duplicate this?





source:
  path: ..

build:
  number: 0
  script:
    - unset CMAKE_GENERATOR && {{ PYTHON }} -m pip install . -vv  # [not win]
    - {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python {{python}}
    - numpy {{ numpy }}
    - {{ compiler('cxx') }}


  host:
    - cmake
    - ninja
    - python {{python}}
    - numpy {{ numpy }}
    - pip
    - scikit-build-core
    - pybind11 >=2.13.0
    - fmt
    - zeromq
    - nlohmann_json
    - catch2

  run:
    - python {{python}}
    - numpy {{ numpy }}


test:
  imports:
    - aare
  # requires:
  #   - pytest
  # source_files:
  #   - tests
  # commands:
  #   - pytest tests

about:
  summary: An example project built with pybind11 and scikit-build.
  # license_file: LICENSE