name: clang-tidy
on: 
  push:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linting checks
        # find all examples in build/examples and run them
        run: |
          pwd
          mkdir build
          cd build
          cmake ..
          cd ..
          find \(-path "./core/*" -o -path "./file_io/*" \) \( -name "*.cpp" -o -name "*.hpp" \)   -not -path "./python/*" -not -name "*.test.cpp"  -not -name "CircularFifo.hpp" -not -name "ProducerConsumerQueue.hpp" -not -name "VariableSizeClusterFinder.hpp" `| xargs -I {} -n 1 -P 10 clang-tidy --config-file=.clang-tidy -p build {}
          # clang-tidy --config-file=.clang-tidy -p build `find -path "./core/*" \( -name "*.cpp" -o -name "*.hpp"  \) -not -name "*.test.cpp"  -not -name "CircularFifo.hpp" -not -name "ProducerConsumerQueue.hpp" -not -name "VariableSizeClusterFinder.hpp" `
