name: Build and run tests
on: 
  workflow_call:
    inputs:
      use-system-libraries: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        if: ${{ contains(inputs.use-system-libraries, 'ON')}}
        with:
          activate-environment: aare
          environment-file: aare-environment.yml
          python-version: 3.11
      # - name: install dependencies
      #   if: ${{ contains(inputs.use-system-libraries, 'ON')}}
      #   shell: bash -el {0}
      #   run: |
      #     conda info
      #     conda install conda-forge::fmt conda-forge::catch2 conda-forge::pybind11 conda-forge::nlohmann_json
      - name: build
        shell: bash -el {0}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE="Debug" -DAARE_PYTHON_BINDINGS="OFF" -DAARE_SYSTEM_LIBRARIES=${{inputs.use-system-libraries}}
          cmake --build . -j 10
      - name: run tests
        run: |
          cd build/
          ./run_tests
      - name: run examples
        run: |
          pwd
          export PROJECT_ROOT_DIR="."
          ls build/examples/*_example
          find build/examples -name "*_example"  | xargs -I {} -n 1 -t  bash -c {}



