# config file to run multiple jobs in parallel with matrix strategy
name: Config Workflow

on:
  push:

jobs:
  build-and-test:
    strategy:
      # super important if you want to see all results, even if one fails
      # fail-fast is true by default
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        use-system-libraries: ["ON"]
        build-type: ["Release", "Debug"]
        use-python-bindings: ["OFF"]
        # exclude:
        #   # excludes combinations that are not supported
        #   - use-python-bindings: "ON"
        #     use-sanitizers: "ON"
    
    uses: ./.github/workflows/common-workflow.yml # calls the one above 
    with:
      use-system-libraries: ${{ matrix.use-system-libraries }}
      build-type: ${{ matrix.build-type }}
      use-python-bindings: ${{ matrix.use-python-bindings }}
      os: ${{ matrix.os }}
    secrets: inherit

