name: Build pkgs and deploy if on main

on:
  push:
    branches:
     - main
     - developer

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ] # macos-12, windows-2019]
        python-version: ["3.12",]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build=24.9 conda-verify pytest anaconda-client

      - name: Enable upload
        if: github.ref == 'refs/heads/main'
        run: conda config --set anaconda_upload yes
        
      - name: Disable upload
        if: github.ref == 'refs/heads/main'
        run: conda config --set anaconda_upload no

      - name: Build
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: conda build conda-recipe --user slsdetectorgroup --token ${CONDA_TOKEN}

