name: test-formatting
on: 
  push:

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check if files are formatted
        # find all examples in build/examples and run them
        run: |
          pwd
          mkdir build
          cd build
          cmake ..
          cmake --build . --target=check-format

          




