name: test-formatting
on: 
  push:

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check if files are formatted
        # find all .cpp and .hpp files that are not in the build directory
        # and run clang-format on them and diff the output with the original file
        # if there is a difference, the diff will be printed and the action will fail
        run: |
          pwd
          find \( -name "*.cpp" -o -name "*.hpp" \) -not -path "./build/*" | xargs -I {} -n 1  bash -c  'echo {} && ( clang-format -Werror -style="file:.clang-format" {} | diff {} -)' 


          



