name: test-formatting
on: 
  push:

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: aare-environment.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: cmake
        shell: bash -el {0}
        run: |
          mkdir build
          cd build
          cmake .. -DAARE_SYSTEM_LIBRARIES="ON" -DCMAKE_BUILD_TYPE="Debug" -DAARE_PYTHON_BINDINGS="OFF" -DAARE_IN_GITHUB_ACTIONS="ON"
      - name: linting checks
        shell: bash -el {0}
        run: |
          # find all examples in build/examples and run them
          cd build
          cmake --build . --target=check-format
          




